mode: dev
secret: asdasggas
level: 4
port: 9765

dataSource:
  main: you_name:you_password@tcp(you_ip:you_port)/db_name?charset=utf8mb4

redis:
  addr: 127.0.0.1:6379

es:
  esUrl: you_es
  esUsername: ""
  esPassword: ""

email:
  host: smtp.exmail.qq.com
  name: my_name
  email: my_email
  password: ""
